### ISSUE TITLE
EXERCISE 2

### ISSUE THREAD

**Issue by azmanyasin** [STIA1113-A201-GROUP-H/EXERCISES#3]
### **INSTRUCTOR**
Please refer to the following website. Choose 10 questions related to numerical data and expression. Use a variety of inputs and change as many variables and expressions as possible.

https://www.w3resource.com/java-exercises/basic/index1.php

### **SUBMISSION**
1. Coding
2. Input and Output

**Comment by JasonLau278177** [comment]
https://github.com/JasonLau278177/Exercise-/issues/1

**Comment by qingyunleong** [comment]
https://github.com/qingyunleong/Exercise2

**Comment by adamamir** [comment]
https://github.com/adamamir/STIA1113/blob/master/programming1/src/programming1/Exercise2.java

**Comment by Dayat102** [comment]
https://github.com/Dayat102/exercise2.git

**Comment by zhiyi16510** [comment]
https://github.com/zhiyi16510/Exercise2.git

**Comment by ffangtn** [comment]
https://github.com/ffangtn/exercise-2/tree/master/exercises2/src

**Comment by ngchunlong279645** [comment]
https://github.com/ngchunlong279645/EXERCISE/issues/1

**Comment by Saifuddin-s277838** [comment]
https://github.com/Saifuddin-s277838/Exercise1Resume/blob/master/GitHub/src/Exercise2TenQuestions.java

**Comment by qingyunleong** [comment]
https://github.com/qingyunleong/Exercise2

**Comment by YongBoonKeat** [comment]
https://github.com/YongBoonKeat/EXERCISE2/blob/master/Exercise/src/Exercise2.java
https://github.com/YongBoonKeat/EXERCISE2/blob/master/Exercise/Output

**Comment by herenika** [comment]
https://github.com/herenika/Exercise.git

**Comment by ngchunlong279645** [comment]
https://github.com/ngchunlong279645/EXERCISE/tree/master/exercise2/src

**Comment by ChongCheeTwau278751** [comment]
https://github.com/ChongCheeTwau278751/Exercise-2

**Comment by Ainurnatasya17** [comment]
https://github.com/Ainurnatasya17/Exercise2.git

**Comment by Esyaa00** [comment]
https://github.com/Esyaa00/Assignment2.git
![Exercise 2](https://user-images.githubusercontent.com/73225960/97838952-31febd00-1d1c-11eb-9de3-ca43df3cf7f5.png)

**Comment by Esyaa00** [comment]
https://github.com/Esyaa00/Assignment2.git

**Comment by LimKitEeNatelie** [comment]
https://github.com/LimKitEeNatelie/EXERCISES.git

**Comment by ChongCheeTwau278751** [comment]
> https://github.com/ChongCheeTwau278751/Exercise-2

**Comment by tehyeexin** [comment]
1. https://github.com/tehyeexin/EXERCISES-STIA1113/tree/master/Exercises2/src
2. https://github.com/tehyeexin/EXERCISES-STIA1113/issues/1

**Comment by khooyenni** [comment]
https://github.com/khooyenni/Exersice-2.git

**Comment by jiakee1026** [comment]
https://github.com/jiakee1026/Exercises2

**Comment by WoonZhunPing** [comment]
https://github.com/WoonZhunPing/EXERCISES

**Comment by piqahamir** [comment]
https://github.com/piqahamir/EXERCISE-2.git

**Comment by NGZIHENG** [comment]
https://github.com/NGZIHENG/exercise2.git

**Comment by leetzongying** [comment]
https://github.com/leetzongying/Exercise2

**Comment by lohsiewchin** [comment]
https://github.com/kellyloh811/Programming1Exercises/tree/master/Exercise2/src
https://github.com/kellyloh811/Programming1Exercises/issues/1

**Comment by FatinShamas** [comment]
https://github.com/FatinShamas/EXERCISES_.git

**Comment by athirahbazilah** [comment]
https://github.com/athirahbazilah/Exercise2.git

**Comment by wanizzat836** [comment]
https://github.com/wanizzat836/EXERCISE.git

**Comment by chunkhai8** [comment]
https://github.com/chunkhai8/Exersice2

**Comment by izannuddin** [comment]
https://github.com/izannuddin/exercises2.git

**Comment by shakir277980** [comment]
https://github.com/shakir277980/exercise2.git

**Comment by SNaqilah** [comment]
https://github.com/SNaqilah/EXERSICES.git

**Comment by Pee278802** [comment]
https://github.com/Pee278802/Exercise-2

**Comment by ChunWai279321** [comment]
https://github.com/ChunWai279321/EXERCISES/blob/master/Exercise/src/Exercise2.java

**Comment by Nurafiza058** [comment]
https://github.com/Nurafiza058/ExcerciseProg1/tree/main/Excercise%202

**Comment by puteriwan** [comment]
https://github.com/puteriwan/Exercise/blob/master/Exercise/src/Week3.java

**Comment by nurqurratuaini** [comment]
https://github.com/nurqurratuaini/exercises/tree/main/Exercise2

**Comment by MohamadAmmar123** [comment]
https://github.com/MohamadAmmar123/STIA1113/tree/master/Exercise2

**Comment by Chong-LeeTing** [comment]
https://github.com/Chong-LeeTing/Exercise2.git
